
# MLflow configuration
MLFLOW_PORT=5000
MLFLOW_BUCKET_NAME=mlflow

# MinIO access keys - these are needed by MLflow
MINIO_ACCESS_KEY=qOGuTLWdapSgtc11WbG8
MINIO_SECRET_ACCESS_KEY=HJG0ZM0M7lMmbOigGAD6hMtUoDVLInkYeQvKTf2z

# MinIO configuration
MINIO_ROOT_USER='minio_user'
MINIO_ROOT_PASSWORD='minio_pwd'
MINIO_ADDRESS=':9000'
MINIO_STORAGE_USE_HTTPS=False
MINIO_CONSOLE_ADDRESS=':9001'
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001